// ─── Stock Database for Autocomplete ───

export const STOCK_DATABASE: { ticker: string; name: string; sector: string }[] = [
  { ticker: "AAPL", name: "Apple Inc.", sector: "Technology" },
  { ticker: "MSFT", name: "Microsoft Corporation", sector: "Technology" },
  { ticker: "NVDA", name: "NVIDIA Corporation", sector: "Semiconductors" },
  { ticker: "GOOGL", name: "Alphabet Inc.", sector: "Technology" },
  { ticker: "AMZN", name: "Amazon.com Inc.", sector: "Consumer" },
  { ticker: "META", name: "Meta Platforms Inc.", sector: "Technology" },
  { ticker: "TSLA", name: "Tesla Inc.", sector: "Automotive" },
  { ticker: "AVGO", name: "Broadcom Inc.", sector: "Semiconductors" },
  { ticker: "AMD", name: "Advanced Micro Devices", sector: "Semiconductors" },
  { ticker: "ANET", name: "Arista Networks", sector: "Networking" },
  { ticker: "MRVL", name: "Marvell Technology", sector: "Semiconductors" },
  { ticker: "SNDK", name: "SanDisk Corporation", sector: "Storage" },
  { ticker: "CRWD", name: "CrowdStrike Holdings", sector: "Cybersecurity" },
  { ticker: "SNOW", name: "Snowflake Inc.", sector: "Cloud Data" },
  { ticker: "NET", name: "Cloudflare Inc.", sector: "Cloud" },
  { ticker: "DDOG", name: "Datadog Inc.", sector: "Cloud" },
  { ticker: "COIN", name: "Coinbase Global", sector: "Crypto" },
  { ticker: "SHOP", name: "Shopify Inc.", sector: "E-Commerce" },
  { ticker: "SQ", name: "Block Inc.", sector: "Fintech" },
  { ticker: "SOFI", name: "SoFi Technologies", sector: "Fintech" },
  { ticker: "IONQ", name: "IonQ Inc.", sector: "Quantum Computing" },
  { ticker: "SMCI", name: "Super Micro Computer", sector: "AI Infra" },
  { ticker: "ARM", name: "Arm Holdings", sector: "Semiconductors" },
  { ticker: "MU", name: "Micron Technology", sector: "Memory" },
  { ticker: "QCOM", name: "Qualcomm Inc.", sector: "Semiconductors" },
  { ticker: "INTC", name: "Intel Corporation", sector: "Semiconductors" },
  { ticker: "TSM", name: "Taiwan Semiconductor", sector: "Semiconductors" },
  { ticker: "LLY", name: "Eli Lilly and Company", sector: "Pharma" },
  { ticker: "UNH", name: "UnitedHealth Group", sector: "Healthcare" },
  { ticker: "V", name: "Visa Inc.", sector: "Payments" },
  { ticker: "JPM", name: "JPMorgan Chase & Co.", sector: "Banking" },
  { ticker: "MA", name: "Mastercard Inc.", sector: "Payments" },
  { ticker: "WMT", name: "Walmart Inc.", sector: "Retail" },
  { ticker: "COST", name: "Costco Wholesale", sector: "Retail" },
  { ticker: "DIS", name: "Walt Disney Company", sector: "Entertainment" },
  { ticker: "NFLX", name: "Netflix Inc.", sector: "Entertainment" },
  { ticker: "BA", name: "Boeing Company", sector: "Aerospace" },
  { ticker: "GS", name: "Goldman Sachs Group", sector: "Banking" },
  { ticker: "PANW", name: "Palo Alto Networks", sector: "Cybersecurity" },
  { ticker: "PLTR", name: "Palantir Technologies", sector: "AI Software" },
  { ticker: "RKLB", name: "Rocket Lab USA", sector: "Space" },
  { ticker: "ACHR", name: "Archer Aviation", sector: "eVTOL" },
  { ticker: "CELH", name: "Celsius Holdings", sector: "Beverages" },
  { ticker: "LITE", name: "Lumentum Holdings", sector: "Photonics" },
];
